### ISSUE TITLE
starting point for the AdvancedMH.RWMH

### ISSUE THREAD

**Issue by zhen0z** [TuringLang/AdvancedMH.jl#104]
Hi, 

I'd like to give the AdvancedMH.RWMH a starting point, and then random walk to find the solution, something like this:

initial_values = [2.0, 5.0, 3.5, 7.5, 1.0] 
rwmh = AdvancedMH.RWMH(5)
external_sampler = externalsampler(rwmh)
chain = sample(model, external_sampler, MCMCDistributed(), 1, 1, initial=initial_values)

is it possible to achieve this? Thanks.

**Comment by torfjelde** [comment]
Yep! You can do this with the `initial_params` argument to `sample`:) So just do `initial_params` instead of `initial` and you should be good :+1:

**Comment by zhen0z** [comment]
That's great, thanks for the advice!

Tor Erlend Fjelde ***@***.***> 于2024年12月4日周三 18:47写道：

**Comment by torfjelde** [comment]
Is it okay if we close the issue then?:)

**Comment by zhen0z** [comment]
Absolutely, thanks!

Tor Erlend Fjelde ***@***.***>于2024年12月5日 周四07:43写道：
