### ISSUE TITLE
Skipping the Hastings computation for symmetric proposals

### ISSUE THREAD

**Issue by luiarthur** [TuringLang/AdvancedMH.jl#41]
In [here][1] and [here][2], to compute the log acceptance probability (`loga`), the proposal density evaluated at the proposed and previous sample is always computed. However, this is not necessary if the proposal is symmetric, since `q(spl, params_prev, params) - q(spl, params, params_prev) == 0`.

Is there a reasonable way to check if the proposal is symmetric and, if it is, skip the Hastings part of the log acceptance probability computation?

I noticed this when looking at #39. The proposal is always Normal, so `q` doesn't need to be computed. I understand that there really isn't a computation bottleneck. But for multivariate proposals, it could be nice to avoid this unnecessary computation.

[1]: https://github.com/TuringLang/AdvancedMH.jl/blob/2bad97c703b6ae44fc8af5741e9ee36a01170671/src/mh-core.jl#L206
[2]: https://github.com/TuringLang/AdvancedMH.jl/blob/2bad97c703b6ae44fc8af5741e9ee36a01170671/src/mh-core.jl#L207

**Comment by cpfiffer** [comment]
We could probably dispatch on certain proposal types -- if it's `Normal` or `MvNormal`, for example, we could just skip this computation. Are there any other commonly used symmetric distributions we can add to the list?

**Comment by luiarthur** [comment]
For continuous unconstrained random variables, `Normal` and `MvNormal` are the go-to.

A Uniform proposal is also sometimes used. (e.g. `x_proposed ~ Uniform(x_current - a, x_currentt + a)`, where `a` is a tuning parameter that functions like the Normal proposal variance.) A caveat is that you need to be mindful of the support of the random variable. But using a Uniform should be kosher if the rv is unconstrained.

I've heard of symmetric heavy-tailed distribution like student-t or Cauchy being used as proposal distributions, though I haven't seen that in practice. Supposedly, you can better explore the tails of the distribution with a heavy-tailed proposal.
