### ISSUE TITLE
StructArrays missing in README for MALA

### ISSUE THREAD

**Issue by briandepasquale** [TuringLang/AdvancedMH.jl#47]
I just noticed that my MALA example in the README file is missing

`using StructArrays`

Is there a simple way to fix this, or do I need to submit a new PR?

**Comment by cpfiffer** [comment]
Fixed it here: https://github.com/TuringLang/AdvancedMH.jl/commit/efebf2fb975190bca9a5bec98e6245fa7ec12da8
