### ISSUE TITLE
Is Emcee implemented?

### ISSUE THREAD

**Issue by astrozot** [TuringLang/AdvancedMH.jl#69]
From the code I see there is an emcee.jl file which seems to implement (part of?) the affine-invariant MCMC algorithm, aka Emcee in Python. Is this work on progress or is it already usable? I do not see any mention in the Readme file. 

If that helps, the same algorithm (with just the parallel stretch step) is implemented in 

https://github.com/madsjulia/AffineInvariantMCMC.jl

The code is very simple and of course does not try to comply to the MCMCInterface.

**Comment by astrozot** [comment]
@devmotion thank you for your quick reply! From the test code you mentioned I see one need to specify a `StretchProposal`, which, if I understand correctly, is essentially used only to draw the initial positions of the walkers (and to specify the stretch parameter `a`, which by default is two). I believe it would be useful to have the possibility to directly provide the initial positions of the walkers: in many situations one perform a quick inference (for example on a simpler but similar model) and the convergence would be much faster if one starts from the "right" positions.

**Comment by astrozot** [comment]
As an additional point regarding the emcee implementation, if I am not mistaken, the code perform in a for-loop the update of all walkers:

https://github.com/TuringLang/AdvancedMH.jl/blob/9b3ac5a8909e605bb5fa720fb438cc751fe5bbb9/src/emcee.jl#L45-L55

However, from what I know the updates for the Emcee algorithm should be performed in series, by advancing each walker one by one. This is mentioned in the paper

https://arxiv.org/pdf/1202.3665.pdf

at p. 7, subsection "The parallel stretch move", where the authors claim that the naïve parallel update "subtly violates detailed balance".

**Comment by cpfiffer** [comment]
> I believe it would be useful to have the possibility to directly provide the initial positions of the walkers: in many situations one perform a quick inference (for example on a simpler but similar model) and the convergence would be much faster if one starts from the "right" positions.

If you want to do this, you should be able to provide a degenerate (or nearly degenerate) proposal for the walkers centered around the location you want, i.e.

```julia
# Import the package.
using AdvancedMH
using Distributions
using MCMCChains

using LinearAlgebra

# Generate a set of data from the posterior we want to estimate.
data = rand(Normal(0, 1), 30)

# Define the components of a basic model.
insupport(θ) = θ[2] >= 0
dist(θ) = Normal(θ[1], θ[2])
density(θ) = insupport(θ) ? sum(logpdf.(dist(θ), data)) : -Inf

# Construct a DensityModel.
model = DensityModel(density)

# Set up emcee
guess = zeros(2) # Change this to use your "optimal" proposals.
spl = Ensemble(100, StretchProposal(MvNormal(guess, 0.0001*I)))
chain = sample(model, spl, 100000; param_names=["μ", "σ"])
```

As to this part:

> However, from what I know the updates for the Emcee algorithm should be performed in series, by advancing each walker one by one. This is mentioned in the paper

I'm not sure what you're discussing -- this is a serial update, not a parallel one. Could you elaborate a little more about what you're expecting to see?

**Comment by astrozot** [comment]
Thank you for the solution with the initial positions of the walkers. Just to be double sure: the `spl` ensemble provided to the `sample` method is only used as a sampling proposal for the initial step and is not as a prior in all steps, correct?

Regarding the serial/parallel update, it looks to me that the way it is implemented it is effectively parallel: in each step, you move all walkers using, for the computations, the locations of the walkers at the previous steps. In fact, you define `new_walkers` as an uninitialised vector similar to `walkers`, and then initialise each of them using the complementary set `other_walkers`. However, `other_walkers` is based on `walkers`. For example, when updating the position of the 3rd walker, you might randomly pick up from the complementary set the 2nd walker, and then you would use the *old position* of the 2nd walker in the computation rather than the new one. This is not what the original algorithm prescribes, and from the reference I gave it seems it will violate the detailed balance. You can check this point in the original paper

[Goodman, Jonathan R and Jonathan Weare. “Ensemble samplers with affine invariance.” (2010)](https://www.semanticscholar.org/paper/Ensemble-samplers-with-affine-invariance-Goodman-Weare/4311c875c04b091acba45de428b68daa66b69a3c)

Check in particular the first equation at the top of p. 69 of the [original paper](https://msp.org/camcos/2010/5-1/camcos-v5-n1-p04-s.pdf), where the authors define the complementary set for $X_k$ at the step $t$: you will notice that this set includes *updated* locations $X_1(t+1), X_2(t+1), \dots, X_{k-1}(t+1)$ for all walkers before $k$.

**Comment by kaandocal** [comment]
I agree with @astrozot, the current implementation is different from the proposal in the paper. It's a form of Gibbs sampling and you have to use the walkers you already sampled in a round to update the remaining ones. I am currently using Emcee myself and override `AdvancedMH.propose` manually to fix this:

```julia
function propose(
    rng::Random.AbstractRNG,
    spl::Ensemble,
    model::DensityModel,
    walkers::Vector{<:Transition},
)
    new_walkers = copy(walkers)            # Initialise walkers

    others = 1:(spl.n_walkers - 1)
    for i in 1:spl.n_walkers
        walker = new_walkers[i]            # This is equal to walkers[i]
        idx = mod1(i + rand(rng, others), spl.n_walkers)
        other_walker = new_walkers[idx]    # This is the main change
        new_walkers[i] = move(rng, spl, model, walker, other_walker)
    end

    return new_walkers
end
```
It would probably be a good idea to fix this in the repo.
