### ISSUE TITLE
RW prior on vectors

### ISSUE THREAD

**Issue by patwa67** [TuringLang/AdvancedMH.jl#94]
How can I apply random walk priors to a vector (beta[1:10]) using AdvancedMH in Turing? Not working sampling code is as follows:
```
chain = sample(
    model,
    MH(
        :sigmae => AdvancedMH.RandomWalkProposal(Normal(0, 0.1)),
        :alpha => AdvancedMH.RandomWalkProposal(Normal(0, 0.1)),
        :beta => AdvancedMH.RandomWalkProposal(Normal(0, 0.1)),
    ),
    1_000
)
```

**Comment by penelopeysm** [comment]
Hi @patwa67! Sorry nobody replied to you in good time.

You need to give a multivariate distribution inside the proposal. See e.g. https://github.com/TuringLang/AdvancedMH.jl/blob/44427837c23a0feab8265aa98afbd635e55b1db7/src/proposal.jl#L41-L56

so if `x` is a 10-element vector then `rand(rng, proposal)` should give a 10-element vector.

```julia
using Turing
using AdvancedMH
using LinearAlgebra: I

@model function f()
    a ~ Normal(0, 1)
    x ~ MvNormal(fill(a, 10), I)
end

chain = sample(
    f(),
    MH(
        :a => AdvancedMH.RandomWalkProposal(Normal(0, 1)),
        :x => AdvancedMH.RandomWalkProposal(MvNormal(zeros(10), I)),
    ),
    1000
)
```

Tested on:

```julia
julia> versioninfo()
Julia Version 1.10.5
Commit 6f3fdf7b362 (2024-08-27 14:19 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)

(ppl) pkg> st
Status `~/ppl/Project.toml`
  [5b7e9947] AdvancedMH v0.8.3
  [fce5fe82] Turing v0.34.1
```

I'm going to close this, but please feel free to reopen if you have other questions or bugs. Do specify the model as well as that will make it possible to reproduce (the call to `sample` needs to match the way the model is defined).
